#!/bin/bash
# Freecash Microtask Platform - Setup Guide
# Note: Registration must be done manually via browser

echo "📋 Freecash Microtask Platform Setup Guide"
echo "==========================================="
echo ""
echo "⚠️ IMPORTANT: Registration must be done manually!"
echo ""
echo "📝 Registration Steps:"
echo "1. Go to https://freecash.com/"
echo "2. Click 'Sign Up' button"
echo "3. Use one of these methods:"
echo "   - Email: ${HACKERONE_EMAIL:-potosopotosolo@gmail.com}"
echo "   - Google account"
echo "   - Steam account"
echo "4. Verify your email address"
echo ""
echo "🔧 After registration:"
echo "1. Complete profile to get more tasks"
echo "2. Verify identity when requesting first cashout"
echo "3. Link PayPal for withdrawals: potosopotosolo@gmail.com"
echo ""
echo "💰 Earning Methods:"
echo "   - Surveys: \$0.50-5 per survey"
echo "   - Tasks (offers, games): \$0.10-10 per task"
echo "   - Daily bonuses for consistency"
echo "   - Realistic: \$1-20/month (ต้องทำเยอะถึงจะได้มาก)"
echo ""
echo "⚠️ Note: ถอนเงินต้องยืนยันตัวตน (KYC) ก่อน"