#!/bin/bash
# Prolific Survey Platform - Setup Guide
# Note: Registration must be done manually via browser

echo "📋 Prolific Survey Platform Setup Guide"
echo "======================================="
echo ""
echo "⚠️ IMPORTANT: Registration must be done manually!"
echo ""
echo "📝 Registration Steps:"
echo "1. Go to https://www.prolific.com/"
echo "2. Click 'Sign Up' → SELECT 'PARTICIPANT' (หรือ 'Take studies') ***"
echo "   *** ต้องเลือก Participant ไม่ใช่ Researcher! ***"
echo "   - Researcher = คนสร้าง study (ไม่ใช่เรา)"
echo "   - Participant = คนทำ survey ได้เงิน (เราต้องเลือกอันนี้)"
echo "3. Use email: ${HACKERONE_EMAIL:-potosopotosolo@gmail.com}"
echo "4. Verify email via link sent to inbox"
echo "5. Complete your profile (demographics affect available studies)"
echo ""
echo "🔧 After registration is approved:"
echo "1. Verify your email address"
echo "2. Set up payment method (PayPal: potosopotosolo@gmail.com)"
echo "3. Start finding studies to participate in"
echo ""
echo "💰 Earning Potential:"
echo "   - Typical surveys: £5-15 per study"
echo "   - Academic surveys pay consistently"
echo "   - Part-time: £100-500/month possible"
echo ""
echo "📚 Documentation saved in SARAhack.md"