#!/bin/bash
# SARAhack - Report to HTML & Upload Script
# แปลง .md เป็น HTML และอัพโหลดไป tmpfiles.org (free permanent hosting)

set -e

DISCORD_WEBHOOK="https://discord.com/api/webhooks/1512524218871447592/ufbSsNL_4ebXM8EMQlRyEunKg6EH_SIKVo7ulw8olRygPtgda1R4-Gji56dYt9fZR_Fe"
REPORTS_DIR="/home/runner/workspace/reports"
HTML_DIR="/tmp/sarahack_reports"

# Create temp directory
mkdir -p "$HTML_DIR"

# Convert single markdown file to text (HTML content)
convert_to_html() {
    local md_file="$1"
    local basename=$(basename "$md_file" .md)
    local txt_file="$HTML_DIR/${basename}.txt"
    
    # Read content
    local content=$(cat "$md_file")
    
    # Convert markdown to plain text with HTML formatting
    local html=$(echo "$content" | node -e "
const fs = require('fs');
let content = fs.readFileSync('/dev/stdin', 'utf8');

// Escape HTML
content = content.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Headers
content = content.replace(/^# (.*)$/gm, '=== $1 ===');
content = content.replace(/^## (.*)$/gm, '== $1 ==');
content = content.replace(/^### (.*)$/gm, '= $1 =');

// Bold and italic
content = content.replace(/\\*\\*(.*?)\\*\\*/g, '**$1**');
content = content.replace(/\\*(.*?)\\*/g, '*$1*');

// Code blocks - wrap in box
content = content.replace(/\\\n\\\n\\\n/g, '\n\n>>> $1 <<<\n\n');

// Inline code
content = content.replace(/\\\n/g, '|$1|');

// Links
content = content.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '$1 ($2)');

// Tables - basic
content = content.replace(/\\|---.*\\|/g, '');
content = content.replace(/\\|(.+)\\|/g, '| $1 |');

// Paragraphs
content = content.replace(/\\n\\n/g, '\n\n');

// List items
content = content.replace(/^- (.*)$/gm, '* $1');

// Horizontal rule
content = content.replace(/^---$/gm, '─────────────────────────────');

console.log(content);
")
    
    # Save as .txt file (tmpfiles.org accepts .txt)
    cat > "$txt_file" << HTMLEOF
================================================================================
                        SARAhack Vulnerability Report
================================================================================

$html

--------------------------------------------------------------------------------
Generated by SARAhack - Bug Bounty Automation Framework
Report ID: $basename | Date: $(date '+%Y-%m-%d')
================================================================================
HTMLEOF
    
    echo "$txt_file"
}

# Upload to tmpfiles.org (free permanent hosting)
upload_tmpfiles() {
    local file="$1"
    local result=$(curl -s --max-time 60 -F "file=@${file}" "https://tmpfiles.org/api/v1/upload" 2>&1)
    # Parse JSON response: {"status":"success","data":{"url":"https://..."}}
    local url=$(echo "$result" | node -e "
const data = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
console.log(data.status === 'success' ? data.data.url : 'FAILED');
")
    echo "$url"
}

# Send to Discord
send_to_discord() {
    local report_name="$1"
    local download_url="$2"
    local report_id="$3"
    
    local payload=$(cat << PAYLOAD
{
    "username": "SARAhack Uploader",
    "embeds": [{
        "title": "📄 Report Ready: $report_name",
        "color": 3447003,
        "fields": [
            {"name": "Report ID", "value": "$report_id", "inline": true},
            {"name": "Format", "value": "TXT (viewable in browser)", "inline": true}
        ],
        "description": "Click below to download the report:\\n\\n[📥 Download Report]($download_url)\\n\\nOr open the link directly in your browser.",
        "footer": {"text": "SARAhack v1.0 - Report Generator | tmpfiles.org (permanent)"}
    }]
}
PAYLOAD
)
    
    curl -s -X POST "$DISCORD_WEBHOOK" -H "Content-Type: application/json" -d "$payload" 2>&1
}

# Main function
main() {
    echo "=== SARAhack Report Uploader (tmpfiles.org) ==="
    echo "Reports directory: $REPORTS_DIR"
    echo ""
    
    # Get report files
    local reports=$(ls "$REPORTS_DIR"/new_*.md 2>/dev/null | head -10)
    local count=$(echo "$reports" | wc -l)
    
    echo "Found $count report files to process"
    echo ""
    
    local uploaded=0
    local failed=0
    
    for report_file in $reports; do
        local basename=$(basename "$report_file" .md)
        local report_id=$(echo "$basename" | sed 's/new_//')
        
        echo "[$((uploaded+failed+1))/$count] Processing: $basename"
        
        # Convert to text
        local txt_file=$(convert_to_html "$report_file")
        
        if [ -f "$txt_file" ]; then
            # Upload to tmpfiles.org
            local url=$(upload_tmpfiles "$txt_file")
            
            if echo "$url" | grep -q "tmpfiles.org"; then
                echo "  ✓ Uploaded: $url"
                send_to_discord "$basename" "$url" "$report_id"
                uploaded=$((uploaded+1))
            else
                echo "  ✗ Upload failed: $url"
                failed=$((failed+1))
            fi
        else
            echo "  ✗ Conversion failed"
            failed=$((failed+1))
        fi
        
        echo ""
    done
    
    echo "=== Complete ==="
    echo "Uploaded: $uploaded"
    echo "Failed: $failed"
}

# Show help
show_help() {
    echo "
SARAhack Report Uploader - Usage:
  $0 [options]
  
Options:
  --all       Upload all reports (default: first 10)
  --id=N      Upload specific report by ID
  --list      List available reports
  --help      Show this help

Examples:
  $0 --all          Upload first 10 reports
  $0 --id=24        Upload report ID 24 (stripe_cors)
  $0 --list         List all reports
    "
}

# Parse arguments
case "${1:-}" in
    --all)
        main
        ;;
    --id=*)
        id="${1#*=}"
        md_file=$(ls "$REPORTS_DIR"/new_*${id}*.md 2>/dev/null | head -1)
        if [ -f "$md_file" ]; then
            basename=$(basename "$md_file" .md)
            txt_file=$(convert_to_html "$md_file")
            url=$(upload_tmpfiles "$txt_file")
            if echo "$url" | grep -q "tmpfiles.org"; then
                echo "✓ Uploaded: $url"
                send_to_discord "$basename" "$url" "$id"
            else
                echo "✗ Failed: $url"
            fi
        else
            echo "Report not found: $id"
        fi
        ;;
    --list)
        echo "Available reports:"
        ls -1 "$REPORTS_DIR"/new_*.md 2>/dev/null | sed 's|.*/||' | sed 's/.md$//'
        ;;
    --help|-h)
        show_help
        ;;
    *)
        main
        ;;
esac